# Generated by Django 3.2.3 on 2021-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A classroom with that name already exists.'}, help_text='Enter any valid classroom name. It is usually contains branch name, section and subject.', max_length=35, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
